[package]
name = "exec-trace"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# CORRECTED: Use the modern 'aya-ebpf' crate
aya-ebpf = "0.2"
aya-log-ebpf = "0.2"
sentinel-common = { path = "../common" }

# This section is intentionally left blank in the modern system
[lib]
