[package]
name = "exec-trace"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# CORRECTED: Use the latest published versions
aya-ebpf = "0.1.2"
aya-log-ebpf = "0.1.2"
sentinel-common = { path = "../common" }

[[bin]]
name = "exec-trace"
path = "exec_trace.c"