[package]
name = "exec-trace"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# CORRECTED: Use the latest published versions, which are 0.1.1
aya-ebpf = "0.1.1"
aya-log-ebpf = "0.1.1"
sentinel-common = { path = "../common" }

[[bin]]
name = "exec-trace"
path = "exec_trace.c"