name: Build and Publish Dev Image

# This allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

# Set the repository owner and image name as environment variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-dev-env

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest