name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # --- THIS IS THE DEFINITIVE FIX ---
      - name: Force Clean Rust Dependency Resolution
        run: |
          # Deep clean: Remove the global cargo caches that might be corrupted.
          # This is the most forceful way to ensure a clean build.
          rm -rf ~/.cargo/registry
          rm -rf ~/.cargo/git

          # Remove the local lock file to be absolutely sure.
          rm -f src/Cargo.lock
          
          # Now, run the build from a 100% clean state.
          cd src
          cargo update
          cargo check --workspace --verbose