name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            libbpf-dev \
            linux-headers-generic \
            libelf-dev

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      # --- THIS IS THE FIX ---
      - name: Install cargo-bpf for build script runner
        run: |
          # Use two separate echo commands to create a valid, multi-line TOML file.
          mkdir -p ~/.cargo
          echo '[net]' > ~/.cargo/config.toml
          echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml
          
          # Now, install the tool.
          cargo install cargo-bpf --git https://github.com/aya-rs/bpf-cargo --branch main

      - name: Check Rust Code
        run: |
          cd src
          cargo check --workspace --verbose