# ==============================================================================
# Project Sentinel: Continuous Integration (CI) Pipeline
#
# Description:
#   This workflow runs on every push and pull request to the main branch.
#   It performs essential checks to maintain code quality and correctness.
# ==============================================================================

name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # --- THIS IS THE DEFINITIVE FIX ---
      - name: Force Clean Rust Dependency Resolution
        run: |
          # This is the most critical step. By deleting the lock file, we force
          # cargo to rebuild its dependency tree from the correct .toml files,
          # ignoring any bad cache from previous failed runs.
          rm -f src/Cargo.lock
          
          # Now, running update and check will use the correct files.
          cd src
          cargo update
          cargo check --workspace --verbose