name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            libbpf-dev \
            linux-headers-generic \
            libelf-dev \
            pkg-config # Add pkg-config for the build from source

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # --- THIS IS THE DEFINITIVE FIX ---
      # Instead of 'cargo install', we build 'cargo-bpf' from a specific
      # git revision that is known to use a non-buggy version of bindgen.
      - name: Build and Install cargo-bpf from source
        run: |
          git clone https://github.com/aya-rs/cargo-bpf.git
          cd cargo-bpf
          # Check out a specific, stable commit
          git checkout 806a646
          # Build and install into the runner's toolchain
          cargo install --path . --force

      - name: Build the eBPF program
        run: make build-bpf

      - name: Check Rust Code
        run: |
          cd src
          cargo check --workspace --verbose