name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            libbpf-dev \
            linux-headers-generic \
            libelf-dev \
            pkg-config

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Checkout Aya repository
        uses: actions/checkout@v4
        with:
          repository: aya-rs/aya
          ref: main
          path: aya-source

      # --- THIS IS THE NEW DEBUGGING STEP ---
      - name: List Directory Contents to Find Correct Path
        run: |
          echo "--- Listing contents of the 'aya-source' directory ---"
          ls -lR aya-source
          echo "------------------------------------------------------"
          # The workflow will stop here so we can analyze the output.
          # The next step will be to use the correct path found in the log.