name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # --- THIS IS THE NEW DEBUGGING STEP ---
      - name: DEBUG - Display Cargo.toml content
        run: |
          echo "--- Contents of src/agent/Cargo.toml ---"
          cat src/agent/Cargo.toml
          echo "----------------------------------------"

      - name: Force Clean Rust Dependency Resolution
        run: |
          rm -rf ~/.cargo/registry
          rm -rf ~/.cargo/git
          rm -f src/Cargo.lock
          cd src
          cargo update
          cargo check --workspace --verbose