name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            libbpf-dev \
            linux-headers-generic \
            libelf-dev \
            pkg-config

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      # --- THIS IS THE DEFINITIVE FIX ---
      - name: Checkout Aya repository (for cargo-bpf source)
        uses: actions/checkout@v4
        with:
          # CORRECT REPOSITORY: The tool lives inside the main 'aya' repo
          repository: aya-rs/aya
          # Use the main branch which is stable
          ref: main
          path: aya-source

      - name: Build and Install cargo-bpf from source
        run: |
          # CORRECT PATH: Go into the checked-out repo, then into the tool's directory
          cd aya-source/cargo-bpf
          cargo install --path . --force

      - name: Build the eBPF program
        run: make build-bpf

      - name: Check Rust Code
        run: |
          cd src
          cargo check --workspace --verbose