name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # --- THIS IS THE NEW STEP ---
      - name: Install cargo-bpf
        run: cargo install cargo-bpf

      - name: Build the eBPF program
        run: make build-bpf

      - name: Force Clean Rust Dependency Resolution
        run: |
          rm -f src/Cargo.lock
          cd src
          cargo update
          cargo check --workspace --verbose