name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            libbpf-dev \
            linux-headers-generic \
            libelf-dev

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      # The build script will automatically compile the eBPF code.
      # No more 'cargo install' or Makefiles needed.
      - name: Check Rust Code
        run: |
          cd src
          cargo check --workspace --verbose